version: '3.8'
services:
#  bot:

  db:
    image: postgres
    restart: always
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  backend:
    networks:
      - default
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app/app

volumes:
  db_data:
networks:
  default:
