"""add cve_id to bdu model

Revision ID: 3fe71999c7f9
Revises: 57d3587f476b
Create Date: 2024-04-03 23:19:12.749271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3fe71999c7f9'
down_revision: Union[str, None] = '57d3587f476b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bdus', sa.Column('cve_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bdus', 'cve_id')
    # ### end Alembic commands ###
