"""Add CWE table

Revision ID: dea7b018a6d0
Revises: bef36b47bfa6
Create Date: 2024-04-02 01:13:37.831648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'dea7b018a6d0'
down_revision: Union[str, None] = 'bef36b47bfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cwe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cwes_created_at'), 'cwes', ['created_at'], unique=False)
    op.create_index(op.f('ix_cwes_cwe_id'), 'cwes', ['cwe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cwes_cwe_id'), table_name='cwes')
    op.drop_index(op.f('ix_cwes_created_at'), table_name='cwes')
    op.drop_table('cwes')
    # ### end Alembic commands ###
